-- DISPARADOR DE SECUENCIA PARA LA TABLA ACCESO
CREATE OR REPLACE TRIGGER SEQ_ACCESO
BEFORE INSERT ON ACCESO FOR EACH ROW
BEGIN
  :NEW.ID := SEQ_ACCESO.NEXTVAL;
END;

-- DISPARADOR DE SECUENCIA PARA LA TABLA ROL
CREATE OR REPLACE TRIGGER SEQ_ROL
BEFORE INSERT ON ROL FOR EACH ROW
BEGIN
  :NEW.ID := SEQ_ROL.NEXTVAL;
END;

-- DISPARADOR DE SECUENCIA PARA LA TABLA PERSONA
CREATE OR REPLACE TRIGGER SEQ_PERSONA
BEFORE INSERT ON PERSONA FOR EACH ROW
BEGIN
  :NEW.ID := SEQ_PERSONA.NEXTVAL;
END;

-- DISPARADOR DE SECUENCIA PARA LA TABLA PAIS
CREATE OR REPLACE TRIGGER SEQ_PAIS
BEFORE INSERT ON PAIS FOR EACH ROW
BEGIN
  :NEW.ID_PAIS := SEQ_PAIS.NEXTVAL;
END;

-- DISPARADOR DE SECUENCIA PARA LA TABLA CIUDAD
CREATE OR REPLACE TRIGGER SEQ_CIUDAD
BEFORE INSERT ON CIUDAD FOR EACH ROW
BEGIN
  :NEW.ID_CIUDAD := SEQ_CIUDAD.NEXTVAL;
END;

-- DISPARADOR DE SECUENCIA PARA LA TABLA DEPARTAMENTO
CREATE OR REPLACE TRIGGER SEQ_DEPARTAMENTO
BEFORE INSERT ON DEPARTAMENTO FOR EACH ROW
BEGIN
  :NEW.ID_DEPARTAMENTO := SEQ_DEPARTAMENTO.NEXTVAL;
END;

-- DISPARADOR DE SECUENCIA PARA LA TABLA HORARIO
CREATE OR REPLACE TRIGGER SEQ_HORARIO
BEFORE INSERT ON HORARIO FOR EACH ROW
BEGIN
  :NEW.ID := SEQ_HORARIO.NEXTVAL;
END;