--Secuencia person
CREATE SEQUENCE SEQ_PERSONA INCREMENT BY 1;

--Secuencia tipo de eps
CREATE SEQUENCE SEQ_TIPO_EPS INCREMENT BY 1;

--Secuencia eps
CREATE SEQUENCE SEQ_EPS INCREMENT BY 1;

--Secuencia paciente
CREATE SEQUENCE SEQ_PACIENTE INCREMENT BY 1;

--Secuencia cuidad
CREATE SEQUENCE SEQ_CIUDAD INCREMENT BY 1;

--Secuencia departamento
CREATE SEQUENCE SEQ_DEPARTAMENTO INCREMENT BY 1;

--Secuencia pais
CREATE SEQUENCE SEQ_PAIS INCREMENT BY 1;

--Secuencia sintomas
CREATE SEQUENCE SEQ_SINTOMAS
INCREMENT BY 1;

--Secuncia horario
CREATE SEQUENCE SEQ_HORARIO INCREMENT BY 1;

--Secuencia farmacia
CREATE SEQUENCE SEQ_FARMACIA INCREMENT BY 1;

--Secuencia Tipo Medicamento
CREATE SEQUENCE SEQ_TIPO_MEDICAMENTO
INCREMENT BY 1;

--Secuencia enfermedad
CREATE SEQUENCE SEQ_ENFERMEDAD INCREMENT BY 1;

--Secuencia citas medicas
CREATE SEQUENCE SEQ_CITAS_MEDICAS INCREMENT BY 1;

--Secuencia medicamento
CREATE SEQUENCE SEQ_MEDICAMENTO INCREMENT BY 1;

--Secuencia medico
CREATE SEQUENCE SEQ_MEDICO INCREMENT BY 1;

--Secuencia tratamiento
CREATE SEQUENCE SEQ_TRATAMIENTO INCREMENT BY 1;

--Secuencia orden hospitalizacion
CREATE SEQUENCE SEQ_ORDEN_HOSPITALIZACION INCREMENT BY 1;

--Secuencia orden examen
CREATE SEQUENCE SEQ_ORDEN_EXAMEN INCREMENT BY 1;

--Secuencia orden cirugia
CREATE SEQUENCE SEQ_ORDEN_CIRUGIA
INCREMENT BY 1;

--Secuencia orden medicamento
CREATE SEQUENCE SEQ_ORDEN_MEDICAMENTO INCREMENT BY 1;

--Secuencia cirugia
CREATE SEQUENCE SEQ_CIRUGIA INCREMENT BY 1;

--Secuencia examen
CREATE SEQUENCE SEQ_EXAMEN INCREMENT BY 1;

--Secuencia resultado examen
CREATE SEQUENCE SEQ_RESULTADO_EXAMEN INCREMENT BY 1;

--Secuencia entrega medicamento
CREATE SEQUENCE SEQ_ENTREGA_MEDICAMENTO INCREMENT BY 1;

--Secuencia quirofano
CREATE SEQUENCE SEQ_QUIROFANO
INCREMENT BY 1;

--Secuencia hospitalizacion
CREATE SEQUENCE SEQ_HOSPITALIZACION INCREMENT BY 1;

--Secuencia cama hospitalizacion
CREATE SEQUENCE SEQ_CAMA_HOSPITALIZACION INCREMENT BY 1;