/*
 * CANTIDAD Y PROMEDIO DE CITAS ATENTIDAS POR MEDICO Y EPS
 */
 -- VISTA
  CREATE OR REPLACE VIEW REPORTES_CARLOS_MARTINEZ2 AS
  SELECT CM.ID CITA, M.ID ID_MEDICO, PA.NOMBRE||' '||PA.APELLIDO NOMBRE_MEDICO, P.ID ID_PACIENTE, PE.NOMBRE||' '||PE.APELLIDO NOMBRE_PACIENTE, EP.NOMBRE EPS,C.NOMBRE CIUDAD, D.NOMBRE DEPARTAMENTO, PS.NOMBRE PAIS 
  FROM CITAS_MEDICAS CM JOIN MEDICO M ON M.ID = CM.MEDICO JOIN PERSONA PA ON PA.ID = M.ID JOIN PACIENTE P ON P.ID = CM.PACIENTE JOIN EPS EP ON EP.ID_EPS = P.EPS_ID_EPS JOIN PERSONA PE ON PE.ID = P.ID JOIN CIUDAD C ON C.ID_CIUDAD = PE.CIUDAD
  JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO = C.DEPARTAMENTO_ID_DEPARTAMENTO JOIN PAIS PS ON PS.ID_PAIS = D.PAIS_ID_PAIS;
            
  -- PROCEDIMIENTO
  CREATE OR REPLACE PROCEDURE CITAS_BY_MEDICO_EPS(newcursor OUT SYS_REFCURSOR)
  AS
    /* VARIABLE QUE CONTENDRA LA CONSULTA SQL DEL REPORTE */ 
    consulta VARCHAR2(600);
    /* CURSOR DONDE ESTARAN TODAS LAS CIUDADES A MOSTRAR EN EL REPORTE */
    CURSOR DATOS IS 
    SELECT E.NOMBRE FROM EPS E;
    /* ALMACENO LOS NOMBRES DE LAS CIUDADES */
    nombres VARCHAR2(600);
  BEGIN
    FOR REG IN DATOS LOOP
      nombres := nombres||''''||REG.NOMBRE||''',';
    END LOOP; 
    /* USAMOS LA FUNCION RTRIM(variable, 'caracter') PARA ELIMINAR UN DETERMINADO CARACTER DEL FINAL DE LA CADENA EN ESTE CASO UNA ,*/
    nombres := RTRIM(nombres, ',');    
    consulta := 'SELECT * FROM (SELECT NOMBRE_MEDICO,CITA,EPS FROM REPORTES_CARLOS_MARTINEZ2)
                PIVOT(COUNT(CITA) AS CANTIDAD FOR EPS IN ('||nombres||')) ORDER BY NOMBRE_MEDICO';
    /* ABRIMOS EL CURSOR CON NUESTRA CONSULTA YA HECHA */
    OPEN newcursor FOR
    consulta;
  END CITAS_BY_MEDICO_EPS;