CREATE OR REPLACE VIEW CantidadPacientes AS 
SELECT CI.NOMBRE Ciudad, DE.NOMBRE Departamento, PS.NOMBRE Pais, count(PA.ID) Total
FROM PACIENTE PA 
JOIN PERSONA PE ON PA.ID=PE.ID 
JOIN CIUDAD CI ON PE.CIUDAD=CI.ID_CIUDAD 
JOIN DEPARTAMENTO DE ON CI.DEPARTAMENTO_ID_DEPARTAMENTO=DE.ID_DEPARTAMENTO
JOIN PAIS PS ON DE.ID_DEPARTAMENTO=PS.ID_PAIS GROUP BY ROLLUP(CI.NOMBRE, DE.NOMBRE, PS.NOMBRE, PA.ID);
