CREATE OR REPLACE VIEW PromedioEPS AS
SELECT E.NOMBRE, count(P.EPS_ID_EPS) PACIENTES,ROUND(count(P.EPS_ID_EPS)/(SELECT COUNT(PA.ID) FROM PACIENTE PA),2) PORCENTAJE,(SELECT COUNT(PA.ID) FROM PACIENTE PA) PACIENTES_HOSPITAL
FROM PACIENTE P RIGHT JOIN EPS E ON P.EPS_ID_EPS = E.ID_EPS
GROUP BY E.NOMBRE;