create or replace view entregados as
SELECT E.NOMBRE EPS, ME.NOMBRE MEDICAMENTO, SUM(DM.CANTIDAD) ENTREGADOS
FROM EPS E JOIN PACIENTE P ON E.ID_EPS=P.EPS_ID_EPS JOIN CITAS_MEDICAS C ON P.ID=C.PACIENTE JOIN 
ORDEN_MEDICAMENTO OM ON OM.CITAS_MEDICAS=C.ID JOIN DETALLE_ORDENMEDICAMENTO DM ON DM.ORDEN_MEDICAMENTO=OM.ID JOIN MEDICAMENTO ME 
ON ME.ID_MEDICAMENTO=DM.MEDICAMENTO JOIN FARMACIA F ON F.ID_FARMACIA=ME.FARMACIA_ID_FARMACIA JOIN FARMACEUTICO FARMA ON F.FARMACEUTICO=FARMA.ID
WHERE DM.ESTADO=1
GROUP BY ROLLUP(E.NOMBRE, ME.NOMBRE) ;