CREATE OR REPLACE VIEW HISTORIALCLINICO AS
SELECT CM.ID, CM.ESTADO, CM.VALORACION, CM.FECHA, CM.HORA,
E.NOMBRE Examen, HO.FECHA_ENTRADA, HO.FECHA_SALIDA, CI.NOMBRE Cirugia, OE.FECHA_REALIZACION Fecha_Examen, OC.FECHA_CIRUGIA Fecha_Cirugia
FROM PACIENTE PA
JOIN PERSONA PE ON PA.ID=PE.ID
JOIN CITAS_MEDICAS CM ON PA.ID=CM.PACIENTE
LEFT JOIN ORDEN_EXAMEN OE ON CM.ID=OE.CITAS_MEDICAS
LEFT JOIN EXAMEN E ON OE.EXAMEN=E.ID_EXAMEN
LEFT JOIN ORDEN_HOSPITALIZACION OH ON CM.ID=OH.HOSPITALIZACION
LEFT JOIN HOSPITALIZACION HO ON OH.HOSPITALIZACION=HO.ID_HOSPITALIZACION
LEFT JOIN ORDEN_CIRUGIA OC ON CM.ID=OC.ID
LEFT JOIN CIRUGIA CI ON OC.CIRUGIA=CI.ID_CIRUGIA;
