create or replace view Inventario as SELECT M.NOMBRE, F.NOMBRE FARMACIA,M.CANTIDAD, NVL(SUM(M.CANTIDAD),0) TOTAL from MEDICAMENTO M  join FARMACIA F
ON F.ID_FARMACIA=M.FARMACIA_ID_FARMACIA JOIN PERSONA P ON F.FARMACEUTICO=P.ID JOIN FARMACEUTICO FARMA ON P.ID=FARMA.ID where F.NOMBRE='La rebaja'
GROUP BY ROLLUP (M.NOMBRE, F.NOMBRE,M.CANTIDAD) ORDER BY TOTAL DESC;